config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:show]
  resources :trip_reports
  resources :check_ins
  resources :hikes
  resources :trailheads do
    resources :hikes, only: [:show, :new]
  end
  root 'application#home'

  get 'trailheads/most-check-ins' => 'trailheads#show'
  
  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: "callbacks"}
  devise_scope :user do 
      get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do 
    get 'logout', to: 'devise/sessions#destroy'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/trailhead.rb
class Trailhead < ApplicationRecord
    has_many :hikes
    has_many :check_ins
    has_many :users, through: :check_ins

    validates :name, presence: true, uniqueness: true
    validates :location, presence: true, uniqueness: true
    validates :amenities, presence: true
    validates :fees, presence: true

    def self.search(query)
        where("name LIKE ?", "%#{query}%")
    end

    def self.most_check_ins
        joins(:check_ins).group("trailheads.id").order("COUNT(*) DESC").select("trailheads.*").limit(1)
    end

end

app/controllers/trailheads_controller.rb
class TrailheadsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_trailhead, except: [:index, :new, :create, :show]

    def index
        @trailheads = Trailhead.all.sort_by{ |th| th.name }
    end

    def show
        if params[:id] == "most-check-ins"
            @trailhead = Trailhead.most_check_ins.first
        else
            set_trailhead
        end
        @hikes = @trailhead.hikes
        @check_ins = @trailhead.check_ins.reverse
    end
     
    def hike
        @hike = Hike.find(params[:hike_id])
        render template: 'hikes/show'
    end

    def new
        @trailhead = Trailhead.new
    end

    def create
        @trailhead = Trailhead.new(trailhead_params)
        @trailhead.creator_id = current_user.id

        if @trailhead.valid?
            @trailhead.save
            redirect_to trailhead_path(@trailhead)
        else
            flash[:errors] = @trailhead.errors.full_messages
            render :new
        end
    end

    def edit
    end
    
    def update    
        @trailhead.update(trailhead_params)
    
        if @trailhead.save
          redirect_to @trailhead
        else
          flash[:errors] = @trailhead.errors.full_messages
          render :edit
        end
    end

    def destroy
      @trailhead.destroy
      redirect_to trailheads_path
    end

    private

    def trailhead_params
        params.require(:trailhead).permit(   :name,
                                            :location,
                                            :amenities,
                                            :fees)
    end

end

app/helpers/trailheads_helper.rb
module TrailheadsHelper
end

app/views/trailheads/_form.html.erb
<%= form_for(trailhead) do |f| %>
    <label class="label">Trailhead Name:</label>
    <%= f.text_field :name %><br><br>

    <label class="label">Location:</label>
    <%= f.text_field :location %><br><br>

    <label class="label">Amenities:</label>
    <%= f.text_field :amenities %><br><br>

    <label class="label">Fees or Permits:</label>
    <%= f.text_field :fees %><br><br>
    <input type="submit" value="Submit" class="button is-primary">
<% end %>

app/views/trailheads/_list.html.erb
<ul>
<% trailheads.each do |th| %>
    <li><%= link_to th.name, trailhead_path(th) %></li>
<% end %>
</ul>

app/views/trailheads/edit.html.erb
<section class="hero is-primary is-bold">
    <div class="hero-body">
        <div class="container">
            <h2 class="subtitle">Edit <%= @trailhead.name %></h2>
        </div>
    </div>
</section>
<br>

<%= render "application/errors" %>

<%= render partial: "form", locals: {trailhead: @trailhead} %>

<br>

<%= form_tag(trailhead_path(@trailhead), method: "delete") do %>
    <input type="submit" value="Delete" class="button is-danger">
<% end %>

app/views/trailheads/index.html.erb
<section class="hero is-primary is-bold">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">All Trailheads</h1>
        </div>
    </div>
</section>
<br>

<div class="columns">
<div class="column">
    <div>
    <strong><%= link_to "Create a New Trailhead", new_trailhead_path %></strong>
    </div>
    <br>
    <div>
    <h3>Want the most popular trailhead?</h3>
    <%= link_to "Click here", trailheads_most_check_ins_path %> to view the trailhead with the most check-ins.
    </div>
</div>

<div class="column">
    <div>
    <%= render partial: "trailheads/list", locals: {trailheads: @trailheads} %>
    </div>
</div>
</div>

app/views/trailheads/new.html.erb
<section class="hero is-primary is-bold">
    <div class="hero-body">
        <div class="container">
            <h2 class="subtitle">New Trailhead Form</h2>
        </div>
    </div>
</section>
<br>

<%= render "application/errors" %>

<%= render partial: "form", locals: {trailhead: @trailhead} %>

app/views/trailheads/show.html.erb
<section class="hero is-primary is-bold">
    <div class="hero-body">
        <div class="container">
            <h1 class="title"><%= @trailhead.name %></h1>
        </div>
    </div>
</section>
<br>
<% if @trailhead.creator_id == current_user.id %>
    <%= link_to "Edit Trailhead", edit_trailhead_path(@trailhead) %> <br>
<% end %>

<div class="columns">
  <div class="column">

        <div>
        <strong>Location:</strong> <%= @trailhead.location %> <br />
        <strong>Amenities:</strong> <%= @trailhead.amenities %> <br />
        <strong>Fees:</strong> <%= @trailhead.fees %> <br />
        </div>
        <br>
        <div>
        <strong>Add a <%= link_to "New Hike", new_trailhead_hike_path(@trailhead) %> at this trailhead</strong>
        </div>

        <% unless @hikes.empty? %>
            <h3>All Hikes at <%= @trailhead.name %></h3>
            <div>
            <%= render partial: "hikes/list", locals: {hikes: @hikes} %>
            </div>
        <% else %>
            <h3>There are no hikes here yet! Add one by following the link above.</h3>
        <% end %>
    </div>

    <div class="column">    

        <div>
        <h3><%= @check_ins.length %> hikers have checked in here!</h3>

        <%= form_tag(check_ins_path, method: "post") do %>
            <%= hidden_field_tag "trailhead_id", @trailhead.id %>
            Here today? <input type="submit" value="Check In" class="button is-primary is-small">
        <% end %>
        </div>

        <% unless @check_ins.empty? %>

            <h3><%= @trailhead.name %> Check-Ins:</h3>

            <ul>
            <% @check_ins.each do |ch| %>
                <li><%= format_ch_date ch %>: <%= link_to ch.user.name, user_path(ch.user) %></li>
            <% end %>
            </ul>
        <% end %>
    </div>
</div>