config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:show]
  resources :trip_reports
  resources :check_ins
  resources :hikes
  resources :trailheads do
    resources :hikes, only: [:show, :new]
  end
  root 'application#home'

  get 'trailheads/most-check-ins' => 'trailheads#show'
  
  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: "callbacks"}
  devise_scope :user do 
      get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do 
    get 'logout', to: 'devise/sessions#destroy'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :hikes
  has_many :check_ins
  has_many :trip_reports
  has_many :trailheads, through: :check_ins

  validates :name, length: { minimum: 2 }
  validates :email, uniqueness: true


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email

      if auth.info.username
        user.name = auth.info.username
      else
        user.name = auth.info.name
      end
      
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find_by(id: params[:id])
        @hikes = @user.hikes.reverse
        @trip_reports = @user.trip_reports.reverse
        @check_ins = @user.check_ins.reverse
        @trailheads = @user.trailheads.reverse
    end
    
end

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<% unless @hikes.empty? %>
    <h3>Hikes Published by <%= @user.name %>:</h3>
    <%= render partial: "hikes/list", locals: {hikes: @hikes} %>
<% end %>

<% unless @trailheads.empty? %>
    <h3>Trailheads that <%= @user.name %> has been to:</h3>
    <%= render partial: "trailheads/list", locals: {trailheads: @trailheads.uniq} %>
<% end %>

<% unless @check_ins.empty? %>
    <h3><%= @user.name %>'s Check-Ins:</h3>
    <ul>
    <% @check_ins.each do |ch| %>
        <li><%= format_ch_date ch %>: <%= ch.trailhead.name %></li>
    <% end %>
    </ul>
<% end %>

<% unless @trip_reports.empty? %>
    <h3><%= @user.name %>'s Trip Reports:</h3>
    
    <% @trip_reports.each do |tr| %>

        <article class="media">
        <figure class="media-left">
            <p class="image is-64x64">
                <img class="is-rounded" src="https://i.imgur.com/1lG4sCo.png">
            </p>
        </figure>
        <div class="media-content">
            <div class="content">
            <p>
                <strong><%= format_tr_date tr %>: <%= link_to tr.hike.name, hike_path(tr.hike) %></strong><br>
                <% if tr.rating %>
                <% n = tr.rating %>
                    <%= n %> Stars<br>
                    <% n.times do %>&bigstar;<% end %><br>
                <% end %>
                <br>
                <%= tr.content %>
            </p>
            </div>
        </div>
        </article>

    <% end %>
    
<% end %>