config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:show]
  resources :trip_reports
  resources :check_ins
  resources :hikes
  resources :trailheads do
    resources :hikes, only: [:show, :new]
  end
  root 'application#home'

  get 'trailheads/most-check-ins' => 'trailheads#show'
  
  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: "callbacks"}
  devise_scope :user do 
      get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do 
    get 'logout', to: 'devise/sessions#destroy'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/hike.rb
class Hike < ApplicationRecord
    belongs_to :user
    belongs_to :trailhead
    has_many :trip_reports

    validates :name, presence: true, uniqueness: true
    validates :difficulty, inclusion: { in: %w(Easy Moderate Difficult), message: "%{value} is not a valid difficulty selection." }
    validates :distance, presence: true
    validates :elevation_gain, presence: true
    validates :hike_type, presence: true
    validates :description, length: { in: 50..20000}

    def self.search(query)
        where("name LIKE ?", "%#{query}%")
    end
    
    def self.family_friendly
        where(family_friendly: true)
    end

    def self.dog_friendly
        where(dog_friendly: true)
    end

    def self.beaches
        where(beaches: true)
    end

    def self.wildflowers
        where(wildflowers: true)
    end

    def self.mountains
        where(mountains: true)
    end

    def self.waterfalls
        where(waterfalls: true)
    end

end

app/controllers/hikes_controller.rb
class HikesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_hike, except: [:index, :new, :create]
    skip_before_action :verify_authenticity_token, only: [:destroy]

    def index
      if params[:filter]
        case params[:filter]
        when 'Wildflowers'
          @hikes = Hike.wildflowers
        when 'Beaches'
          @hikes = Hike.beaches
        when 'Mountains'
          @hikes = Hike.mountains
        when 'Waterfalls'
          @hikes = Hike.waterfalls
        when 'Family-friendly'
          @hikes = Hike.family_friendly
        when 'Dog-friendly'
          @hikes = Hike.dog_friendly
        end
      else
        @hikes = Hike.all.sort_by{ |h| h.name }
      end
    end

    def show
        @trailhead = @hike.trailhead
        @trip_reports = @hike.trip_reports.reverse
    end

    def new
        if params[:trailhead_id] && !Trailhead.exists?(params[:trailhead_id])
          redirect_to trailheads_path, alert: "Trailhead not found."
        else
          @hike = Hike.new(trailhead_id: params[:trailhead_id])
        end
    end

    def create
        @hike = Hike.new(hike_params)
        @hike.user_id = current_user.id

        if @hike.valid?
            @hike.save
            redirect_to hike_path(@hike)
        else
            flash[:errors] = @hike.errors.full_messages
            render :new
        end
    end

    def edit
        if params[:trailhead_id]
          th = Trailhead.find_by(id: params[:trailhead_id])
          if th.nil?
            redirect_to trailheads_path, alert: "Trailhead not found."
          else
            @hike = th.hikes.find_by(id: params[:id])
            redirect_to trailhead_hikes_path(th), alert: "Hike not found." if @hike.nil?
          end
        end
    end
    
    def update
        @hike.update(hike_params)
    
        if @hike.save
          redirect_to @hike
        else
          flash[:errors] = @hike.errors.full_messages
          render :edit
        end
    end

    def destroy
      @hike.destroy
      redirect_to hikes_path
    end

    private

    def hike_params
        params.require(:hike).permit(   :name,
                                        :description,
                                        :difficulty,
                                        :distance,
                                        :elevation_gain,
                                        :hike_type,
                                        :waterfalls,
                                        :wildflowers,
                                        :mountains,
                                        :beaches,
                                        :dog_friendly,
                                        :family_friendly,
                                        :image_url,
                                        :trailhead_id)
    end

end

app/helpers/hikes_helper.rb
module HikesHelper

  def boolean_display(hike)
    display_text = nil
    arr = []

    if hike.waterfalls == true
        arr << "Waterfalls"
    end

    if hike.wildflowers == true
        arr << "Wildflowers"
    end

    if hike.mountains == true
        arr << "Mountains"
    end

    if hike.beaches == true
        arr << "Beaches"
    end

    if hike.family_friendly == true
        arr << "Family-friendly"
    end

    if hike.dog_friendly == true
        arr << "Dog-friendly"
    end

    unless arr.empty?
        display_text = arr.join(", ")
    end

    display_text
  end
  
end

app/views/hikes/_form.html.erb
<%= form_for(form_hike) do |f| %>

    <% if form_hike.trailhead.nil? %>
        <label class="label">Hike Trailhead:</label>
        <%= f.select :trailhead_id, options_from_collection_for_select(Trailhead.all, :id, :name) %><br>
        <i>Don't see your trailhead? Create a new trailhead <%= link_to "here.", new_trailhead_path %></i><br><br>
    <% else %>
        <%= hidden_field_tag "hike[trailhead_id]", form_hike.trailhead_id %>
    <% end %>

    <label class="label">Hike Name:</label>
    <%= f.text_field :name %><br><br>

    <label class="label">Difficulty:</label>
    <%= f.select :difficulty, options_for_select([ ['Easy', 'Easy'], ['Moderate', 'Moderate'], ['Difficult', 'Difficult'] ]) %><br><br>

    <label class="label">Distance:</label>
    <%= f.text_field :distance %><br><br>

    <label class="label">Elevation Gain:</label>
    <%= f.text_field :elevation_gain %><br><br>

    <label class="label">Hike Type:</label>
    <%= f.text_field :hike_type %><br><br>

    <label class="label">Image URL:</label>
    <%= f.text_field :image_url %><br>
    <i>Image is optional. Paste the direct link to an image uploaded at another site, like Imgur.</i><br><br>

    <label class="label">Hike Highlights, check all that apply:</label>
    <%= f.check_box :waterfalls %>  Waterfalls<br>
    <%= f.check_box :wildflowers %>  Wildflowers<br>
    <%= f.check_box :mountains %>  Mountains<br>
    <%= f.check_box :beaches %>  Beaches<br>
    <%= f.check_box :dog_friendly %>  Dog-friendly<br>
    <%= f.check_box :family_friendly %>  Family-friendly<br><br>

    <label class="label">Hike Description:</label>
    <%= f.text_area :description, size: "100x30" %><br><br>
    <input type="submit" value="Submit" class="button is-primary">
<% end %>

app/views/hikes/_list.html.erb
<ul>
<% hikes.each do |h| %>
    <li><%= link_to h.name, trailhead_hike_path(h.trailhead, h) %></li>
<% end %>
</ul>

app/views/hikes/edit.html.erb
<section class="hero is-primary is-bold">
    <div class="hero-body">
        <div class="container">
            <h2 class="subtitle">Edit <%= @hike.name %></h2>
        </div>
    </div>
</section>
<br>

<%= render "application/errors" %>

<%= render partial: "form", locals: {form_hike: @hike} %>

<br>

<%= form_tag(hike_path(@hike), method: "delete") do %>
    <input type="submit" value="Delete" class="button is-danger">
<% end %>

app/views/hikes/index.html.erb
<section class="hero is-primary is-bold">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">All Hikes</h1>
        </div>
    </div>
</section>
<br>

<div class="columns">
<div class="column">
    <div>
    <strong><%= link_to "Create a New Hike", new_hike_path %></strong>
    </div>
    <br>
    <div>
    <%= form_tag(hikes_path, method: "get") do %>
        <h3>Filter hikes by features</h3>
        <%= select_tag :filter, options_for_select([ ['Mountains'], ['Beaches'], ['Waterfalls'], ['Wildflowers'], ['Family-friendly'], ['Dog-friendly'] ]) %><br><br>
        <input type="submit" value="Filter Hikes" class="button is-primary"><br>
    <% end %>
    </div>
</div>

<div class="column">
    <div>
    <%= render partial: "list", locals: {hikes: @hikes} %>
    </div>
</div>
</div>

app/views/hikes/new.html.erb
<section class="hero is-primary is-bold">
    <div class="hero-body">
        <div class="container">
            <h2 class="subtitle">New Hike Form</h2>
        </div>
    </div>
</section>
<br>

<%= render "application/errors" %>

<%= render partial: "form", locals: {form_hike: @hike} %>

app/views/hikes/show.html.erb
<section class="hero is-primary is-bold">
    <div class="hero-body">
        <div class="container">
            <h1 class="title"><%= @hike.name %></h1>
        </div>
    </div>
</section>
<br>
<% if @hike.user == current_user %>
    <strong><%= link_to "Edit Hike", edit_hike_path(@hike) %></strong>
<% else %>
    <i>Created by <%= link_to @hike.user.name, user_path(@hike.user) %></i>
<% end %>
<br><br>

<div class="columns">
<div class="column">
    <div>
    <strong>Trailhead:</strong> <%= link_to @trailhead.name, trailhead_path(@trailhead) %> <br>
    <strong>Distance:</strong> <%= @hike.distance %> <br>
    <strong>Elevation Gain:</strong> <%= @hike.elevation_gain %> <br>
    <strong>Type:</strong> <%= @hike.hike_type %> <br>
    <strong>Difficulty:</strong> <%= @hike.difficulty %> <br>
    <strong>Highlights:</strong> <%= boolean_display @hike %> <br>
    <br>
    <strong>Description:</strong><br>
    <%= @hike.description.gsub(/\n/, '<br>').html_safe %> <br />
    </div>
</div>
<div class="column">
    <% if @hike.image_url %>
    <figure>
        <p class="image">
            <img src= "<%= @hike.image_url %>" >
        </p>
    </figure>
    <% end %>
</div>
</div>

<br><br>

<section class="content">
<h3>Leave a Trip Report:</h3>
<%= form_tag(trip_reports_path, method: "post") do %>
    <%= hidden_field_tag "hike_id", @hike.id %>
    <strong>Rating:</strong> <%= select_tag :rating, options_for_select([ [''], ['5 Stars', 5], ['4 Stars', 4], ['3 Stars', 3], ['2 Stars', 2], ['1 Stars', 1] ]) %><br>
    <strong>Trip Report:</strong><br>
    <textarea name="content", rows="10", cols="80"></textarea><br>
    <input type="submit" value="Submit Trip Report" class="button is-primary">
<% end %>
<br>
</section>

<% unless @trip_reports.empty? %>
    <h3><%= @hike.name %> Trip Reports:</h3>
    
    <% @trip_reports.each do |tr| %>

        <article class="media">
            <figure class="media-left">
                <p class="image is-64x64">
                    <img class="is-rounded" src="https://i.imgur.com/1lG4sCo.png">
                </p>
            </figure>
            <div class="media-content">
                <div class="content">
                <p>
                    <strong><%= format_tr_date tr %>: <%= link_to tr.user.name, user_path(tr.user) %></strong><br>
                    <% if tr.rating %>
                    <% n = tr.rating %>
                        <%= n %> Stars<br>
                        <% n.times do %>&bigstar;<% end %><br>
                    <% end %>
                    <br>
                    <%= tr.content %>
                </p>
                </div>
            </div>
        </article>

    <% end %>
<% end %>