config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:show]
  resources :trip_reports
  resources :check_ins
  resources :hikes
  resources :trailheads do
    resources :hikes, only: [:show, :new]
  end
  root 'application#home'

  get 'trailheads/most-check-ins' => 'trailheads#show'
  
  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: "callbacks"}
  devise_scope :user do 
      get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do 
    get 'logout', to: 'devise/sessions#destroy'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HikersApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

  <header>
  <br>
  <nav class="level">
      <% if user_signed_in? %>
      <div class="level-left"> 
        <p class="level-item">
          <%= form_tag(root_path, method: "get") do %>
            <input class="input" type="text" name="query" id="query" placeholder="Find a hike">
            <input type="submit" value="Search" class="button is-primary">
          <% end %>
        </p>
      </div>

      <div class="level-right"
        <p class="level-item">
        <a class="navbar-item"><%= link_to "About", root_path %></a>
        </p>
        <p class="level-item">
        <a class="navbar-item"><%= link_to "All Hikes", hikes_path %></a>
        </p>
        <p class="level-item">
        <a class="navbar-item"><%= link_to "All Trailheads", trailheads_path %></a>
        </p>
        <p class="level-item">
        <a class="navbar-item"><%= link_to "New Hike", new_hike_path %></a>
        </p>
        <p class="level-item">
        <a class="navbar-item"><%= link_to "Log Out", logout_path %></a>
        </p>
        <p>  
                  
        </p>
      </div>

      <% else %>
      <div class="level-left"> 
        <p class="level-item">
        <a class="navbar-item"><%= link_to "Sign Up", signup_path %></a>
        </p>
        <p class="level-item">
        <a class="navbar-item"><%= link_to "Log In", login_path %></a>
        </p>
        <p class="level-item">
        <a class="navbar-item"><%= link_to "Blog", "https://leonorpdx.github.io/cookbook_community_sinatra_project" %></a>
        </p>
        <p class="level-item">
        <a class="navbar-item"><%= link_to "Video", "https://www.youtube.com/watch?v=4tjBlS7e9Ug" %></a>
        </p>
        <p class="level-item">
        <a class="navbar-item"><%= link_to "GitHub", "https://github.com/LeonorPDX/sinatra-crud-cookbook-community/" %></a>
        </p>
      </div>
      <% end %>
    </div>
  </nav>
  </header>



  <section class="section">
    <div class="content">


        <div class="content has-text-centered">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>


      <%= yield %>

    </div>
  </section>

  <footer class="footer">
  <div class="content has-text-centered">
    <p>
      <strong>The Hikers App</strong> by <a href="https://www.linkedin.com/in/leonorcolbert/">Leonor Colbert</a> &copy; 2020
    </p>
  </div>
</footer>
</body>
  
</html>